add access token

diff --git a/.github/workflows/TerraformDeployTest-gotc-test.yml b/.github/workflows/TerraformDeployTest-gotc-test.yml
--- a/.github/workflows/TerraformDeployTest-gotc-test.yml
+++ b/.github/workflows/TerraformDeployTest-gotc-test.yml
@@ -60,6 +60,13 @@ jobs:
            echo "Gcloud auth failed!"
            exit 1
         fi
+        GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
+        if [ -z "${GOOGLE_OAUTH_ACCESS_TOKEN}" ] ; then
+           echo "Generating Gcloud access token failed"
+           exit 1
+        fi
+        echo ::add-mask::${GOOGLE_OAUTH_ACCESS_TOKEN}
+        echo ::set-env name=GOOGLE_OAUTH_ACCESS_TOKEN::${GOOGLE_OAUTH_ACCESS_TOKEN}
 
     # Run Terraform init 
     - name: Terraform init
